services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.example
    environment:
      - IMPORT_TOKEN=${IMPORT_TOKEN:-stepwize_test}
    depends_on:
      - callback

  callback:
    build: ./interface
    ports:
      - "4000:4000"
    env_file:
      - .env
      - .env.example
    environment:
      - IMPORT_TOKEN=${IMPORT_TOKEN:-stepwize_test}
    volumes:
      - ./interface/received.json:/app/received.json
